export const config = {
    words: [
        {text: "apple", syllables: "ap-ple", translation: "蘋果"},
        {text: "accessory", syllables: "ac-ces-so-ry", translation: "配件"},
        {text: "coup", syllables: "coup", translation: "政變"},
        {text: "epitome", syllables: "ep-it-o-me", translation: "典範"},
        {text: "espresso", syllables: "es-pres-so", translation: "濃縮咖啡"},
        {text: "February", syllables: "Feb-ru-ar-y", translation: "二月"},
        {text: "aesthetic", syllables: "aes-thet-ic", translation: "美學的"},
        {text: "podiatrist", syllables: "po-di-a-trist", translation: "足科醫生"},
        {text: "pediatrician", syllables: "pe-di-a-tri-cian", translation: "兒科醫生"},
        {text: "athlete", syllables: "ath-lete", translation: "運動員"},
        {text: "library", syllables: "li-brar-y", translation: "圖書館"},
        {text: "murderer", syllables: "mur-der-er", translation: "兇手"},
        {text: "mischievous", syllables: "mis-chie-vous", translation: "淘氣的"},
        {text: "nuclear", syllables: "nu-cle-ar", translation: "核能的"},
        {text: "remuneration", syllables: "re-mu-ner-a-tion", translation: "報酬"},
        {text: "rural", syllables: "ru-ral", translation: "鄉村的"},
        {text: "scissors", syllables: "scis-sors", translation: "剪刀"},
        {text: "specific", syllables: "spe-cif-ic", translation: "具體的"},
        {text: "squirrel", syllables: "squir-rel", translation: "松鼠"},
        {text: "vocabulary", syllables: "vo-cab-u-lar-y", translation: "詞彙"},
        {text: "quibble", syllables: "quib-ble", translation: "吹毛求疵"},
        {text: "scribble", syllables: "scrib-ble", translation: "潦草的字"},
        {text: "metaphor", syllables: "met-a-phor", translation: "隱喻"},
        {text: "mentor", syllables: "men-tor", translation: "導師"},
        {text: "citation", syllables: "ci-ta-tion", translation: "引用"},
        {text: "colonel", syllables: "colo-nel", translation: "上校"},
        {text: "banana", syllables: "ba-na-na", translation: "香蕉"},
        {text: "computer", syllables: "com-pu-ter", translation: "電腦"},
        {text: "elephant", syllables: "el-e-phant", translation: "大象"},
        {text: "fantastic", syllables: "fan-tas-tic", translation: "極好的"},
        {text: "guitar", syllables: "gui-tar", translation: "吉他"},
        {text: "hospital", syllables: "hos-pi-tal", translation: "醫院"},
        {text: "important", syllables: "im-por-tant", translation: "重要的"},
        {text: "January", syllables: "jan-u-a-ry", translation: "一月"},
        {text: "knowledge", syllables: "know-ledge", translation: "知識"},
        {text: "language", syllables: "lan-guage", translation: "語言"},
        {text: "mountain", syllables: "moun-tain", translation: "山"},
        {text: "newspaper", syllables: "news-pa-per", translation: "報紙"},
        {text: "orchestra", syllables: "or-ches-tra", translation: "管弦樂團"},
        {text: "powerful", syllables: "pow-er-ful", translation: "強大的"},
        {text: "question", syllables: "ques-tion", translation: "問題"},
        {text: "rectangle", syllables: "rec-tan-gle", translation: "矩形"},
        {text: "strategy", syllables: "stra-te-gy", translation: "策略"},
        {text: "telephone", syllables: "tel-e-phone", translation: "電話"},
        {text: "university", syllables: "u-ni-ver-si-ty", translation: "大學"},
        {text: "collage", syllables: "col-lage", translation: "拼貼"},
        {text: "colleague", syllables: "col-league", translation: "同事"},
        {text: "voyage", syllables: "voy-age", translation: "航行"},
        {text: "queue", syllables: "queue", translation: "隊列"},
        {text: "cache", syllables: "cache", translation: "快取"},
        {text: "genre", syllables: "gen-re", translation: "類型"},
        {text: "asterisk", syllables: "as-ter-isk", translation: "星號"},
        {text: "angle", syllables: "an-gle", translation: "角度"},
        {text: "angel", syllables: "an-gel", translation: "天使"},
        {text: "visual", syllables: "vis-u-al", translation: "視覺的"},
        {text: "tortilla", syllables: "tor-til-la", translation: "玉米餅"},
        {text: "cupboard", syllables: "cup-board", translation: "櫥櫃"},
        {text: "hyperbole", syllables: "hy-per-bo-le", translation: "誇張法"},
        {text: "gif", syllables: "gif", translation: "動圖"},
        {text: "mischievous", syllables: "mis-chie-vous", translation: "淘氣的"},
        {text: "subtle", syllables: "sub-tle", translation: "微妙的"},
        {text: "northern", syllables: "north-ern", translation: "北部的"},
        {text: "chassis", syllables: "chas-sis", translation: "底盤"},
        {text: "debut", syllables: "de-but", translation: "首次亮相"},
        {text: "bidet", syllables: "bi-det", translation: "坐浴盆"},
        {text: "hierarchy", syllables: "hi-er-ar-chy", translation: "階級制度"},
        {text: "almond", syllables: "al-mond", translation: "杏仁"},
        {text: "salmon", syllables: "sal-mon", translation: "鮭魚"},
        {text: "island", syllables: "is-land", translation: "島嶼"},
        {text: "photography", syllables: "pho-tog-ra-phy", translation: "攝影"},
        {text: "certificate", syllables: "cer-tif-i-cate", translation: "證書"},
        {text: "suite", syllables: "suite", translation: "套房"},
        {text: "stomach", syllables: "stom-ach", translation: "胃"}
    ],
    phrases: [
        {text: "Good morning", syllables: "Good mor-ning", translation: "早安"},
        {text: "How are you?", syllables: "How are you?", translation: "你好嗎？"},
        {text: "Nice to meet you", syllables: "Nice to meet you", translation: "很高興認識你"},
        {text: "Thank you very much", syllables: "Thank you ve-ry much", translation: "非常感謝"},
        {text: "I'd like to order", syllables: "I'd like to or-der", translation: "我要點餐"},
        {text: "What time is it?", syllables: "What time is it?", translation: "現在幾點？"},
        {text: "See you tomorrow", syllables: "See you to-mor-row", translation: "明天見"},
        {text: "Have a good day", syllables: "Have a good day", translation: "祝你有美好的一天"},
        {text: "Could you help me?", syllables: "Could you help me?", translation: "你可以幫我嗎？"},
        {text: "Where is the bathroom?", syllables: "Where is the bath-room?", translation: "洗手間在哪裡？"},
        {text: "Let me think about it", syllables: "Let me think a-bout it", translation: "讓我想想"},
        {text: "That sounds great", syllables: "That sounds great", translation: "聽起來很棒"},
        {text: "I don't understand", syllables: "I don't un-der-stand", translation: "我不懂"},
        {text: "Can you repeat that?", syllables: "Can you re-peat that?", translation: "你可以再說一次嗎？"},
        {text: "What's the weather like?", syllables: "What's the wea-ther like?", translation: "天氣如何？"},
        {text: "a certificate of achievement", syllables: "a cer-tif-i-cate of a-chieve-ment", translation: "成就證書"},
        {text: "having a stomachache", syllables: "hav-ing a stom-ach-ache", translation: "胃痛"},
        {text: "I like photography", syllables: "I like pho-tog-ra-phy", translation: "我喜歡攝影"},
        {text: "Green Island", syllables: "Green Is-land", translation: "綠島"},
        {text: "apricot kernel drink", syllables: "ap-ri-cot ker-nel drink", translation: "杏仁茶"},
        {text: "almond milk", syllables: "al-mond milk", translation: "杏仁奶"},
        {text: "corporate ladder", syllables: "cor-po-rate lad-der", translation: "企業階梯"},
        {text: "subtle differences", syllables: "sub-tle dif-fer-en-ces", translation: "微妙的差異"},
        {text: "minute differences", syllables: "min-ute dif-fer-en-ces", translation: "細微的差異"},
        {text: "Northern region of Asia", syllables: "North-ern re-gion of Asia", translation: "亞洲北部地區"},
        {text: "South America", syllables: "South Amer-i-ca", translation: "南美洲"},
        {text: "the southern region", syllables: "the south-ern re-gion", translation: "南部地區"},
        {text: "in the local browser cache", syllables: "in the lo-cal brows-er cache", translation: "在本地瀏覽器快取中"},
        {text: "many colleagues", syllables: "man-y col-leagues", translation: "許多同事"},
        {text: "bon voyage", syllables: "bon voy-age", translation: "一路順風"},
        {text: "the world's best universities", syllables: "the world's best u-ni-ver-si-ties", translation: "世界上最好的大學"},
        {text: "questions and answers", syllables: "ques-tions and ans-wers", translation: "問題和答案"},
        {text: "problem and solution", syllables: "prob-lem and so-lu-tion", translation: "問題和解決方法"},
        {text: "cause and effect", syllables: "cause and ef-fect", translation: "因果關係"},
        {text: "newspaper stand", syllables: "news-pa-per stand", translation: "賣報紙攤"},
        {text: "Mountain Dew", syllables: "Moun-tain Dew", translation: "山露（氣泡飲料）"},
        {text: "language acquisition", syllables: "lan-guage ac-qui-si-tion", translation: "語言習得"},
        {text: "knowledgeable person", syllables: "knowl-edge-a-ble per-son", translation: "博學的人"},
        {text: "animal similes", syllables: "an-i-mal sim-i-les", translation: "動物比喻"},
        {text: "interesting metaphor", syllables: "in-ter-est-ing met-a-phor", translation: "有趣的隱喻"},
        {text: "vocabulary word", syllables: "vo-cab-u-lar-y word", translation: "詞彙"},
        {text: "Coca-Cola", syllables: "Co-ca-Co-la", translation: "可口可樂"},
        {text: "Sprite", syllables: "Sprite", translation: "雪碧"},
        {text: "action research", syllables: "ac-tion re-search", translation: "行動研究"},
        {text: "case study", syllables: "case stud-y", translation: "個案研究"},
        {text: "take off", syllables: "take off", translation: "起飛"},
        {text: "rise to my feet", syllables: "rise to my feet", translation: "站起來"},
        {text: "backseat driver", syllables: "back-seat dri-ver", translation: "愛指揮的乘客"},
        {text: "secret recipe", syllables: "se-cret rec-i-pe", translation: "祕密配方"},
        {text: "band-aid solution", syllables: "band-aid so-lu-tion", translation: "權宜之計"},
        {text: "rumor has it", syllables: "ru-mor has it", translation: "據傳"},
        {text: "believe it or not", syllables: "be-lieve it or not", translation: "信不信由你"},
        {text: "continuing education", syllables: "con-tin-u-ing ed-u-ca-tion", translation: "繼續教育"},
        {text: "gender equity", syllables: "gen-der e-qui-ty", translation: "性別平等"},
        {text: "marriage equality", syllables: "mar-riage e-qual-i-ty", translation: "婚姻平權"},
        {text: "honor system", syllables: "hon-or sys-tem", translation: "榮譽制度"},
        {text: "Your Excellency", syllables: "Your Ex-cel-len-cy", translation: "閣下"},
        {text: "career woman", syllables: "ca-reer wom-an", translation: "職業女性"},
        {text: "eavesdrop on our conversation", syllables: "eaves-drop on our con-ver-sa-tion", translation: "偷聽我們的談話"},
        {text: "around the corner", syllables: "a-round the cor-ner", translation: "即將到來"},
        {text: "sick to one's stomach", syllables: "sick to one's stom-ach", translation: "感到反胃"},
        {text: "absent-minded professor", syllables: "ab-sent-mind-ed pro-fes-sor", translation: "健忘的教授"}
    ],
    sentences: [
        {text: "The quick brown fox jumps over the lazy dog.", syllables: "The quick brown fox jumps o-ver the la-zy dog.", translation: "那隻敏捷的棕色狐狸跳過了那隻懶狗。"},
        {text: "I can't believe how fast this year is going by.", syllables: "I can't be-lieve how fast this year is go-ing by.", translation: "我不敢相信今年過得這麼快。"},
        {text: "Would you like to go out for dinner tonight?", syllables: "Would you like to go out for din-ner to-night?", translation: "你今晚想出去吃晚餐嗎？"},
        {text: "She sells seashells by the seashore.", syllables: "She sells sea-shells by the sea-shore.", translation: "她在海邊賣貝殼。"},
        {text: "How much wood would a woodchuck chuck if a woodchuck could chuck wood?", syllables: "How much wood would a wood-chuck chuck if a wood-chuck could chuck wood?", translation: "如果土撥鼠會丟木頭，它能丟多少木頭？"},
        {text: "The early bird catches the worm, but the second mouse gets the cheese.", syllables: "The ear-ly bird catch-es the worm, but the se-cond mouse gets the cheese.", translation: "早起的鳥兒有蟲吃，但第二隻老鼠才能拿到乳酪。"},
        {text: "To be or not to be, that is the question.", syllables: "To be or not to be, that is the ques-tion.", translation: "生存，還是毀滅，這是個問題。"},
        {text: "All that glitters is not gold.", syllables: "All that glit-ters is not gold.", translation: "閃閃發光的不一定是金子。"},
        {text: "You can't judge a book by its cover.", syllables: "You can't judge a book by its co-ver.", translation: "不要以貌取人。"},
        {text: "Life is what happens when you're busy making other plans.", syllables: "Life is what hap-pens when you're bu-sy ma-king o-ther plans.", translation: "當你忙著計畫未來時，生活已經在發生。"},
        {text: "Peter Piper picked a peck of pickled peppers.", syllables: "Pe-ter Pip-er picked a peck of pick-led pep-pers.", translation: "彼得派珀挑了一堆醃辣椒。"},
        {text: "You can't judge a book by its cover.", syllables: "You can't judge a book by its co-ver.", translation: "不要以貌取人。"},
        {text: "Actions speak louder than words.", syllables: "Ac-tions speak loud-er than words.", translation: "行動勝於言語。"},
        {text: "The early bird catches the worm.", syllables: "The ear-ly bird catch-es the worm.", translation: "早起的鳥兒有蟲吃。"},
        {text: "Practice makes perfect.", syllables: "Prac-tice makes per-fect.", translation: "熟能生巧。"},
        {text: "A journey of a thousand miles begins with a single step.", syllables: "A jour-ney of a thou-sand miles be-gins with a sin-gle step.", translation: "千里之行，始於足下。"},
        {text: "The cat sat on the mat.", syllables: "The cat sat on the mat.", translation: "貓坐在墊子上。"},
        {text: "Betty Botter bought some butter, but she said the butter's bitter.", syllables: "Bet-ty Bot-ter bought some but-ter, but she said the but-ter's bit-ter.", translation: "貝蒂·波特買了一些黃油，但她說黃油是苦的。"},
        {text: "Don't cry over spilled milk.", syllables: "Don't cry o-ver spilled milk.", translation: "不要為打翻的牛奶哭泣。"},
        {text: "Every cloud has a silver lining.", syllables: "Ev-e-ry cloud has a sil-ver lin-ing.", translation: "黑暗中總有一線光明。"},
        {text: "Better late than never.", syllables: "Bet-ter late than ne-ver.", translation: "遲到總比不到好。"},
        {text: "Rome wasn't built in a day.", syllables: "Rome was-n't built in a day.", translation: "羅馬不是一天建成的。"},
        {text: "Jack of all trades, master of none.", syllables: "Jack of all trades, mas-ter of none.", translation: "博而不精。"},
        {text: "Birds of a feather flock together.", syllables: "Birds of a feath-er flock to-ge-ther.", translation: "物以類聚，人以群分。"},
        {text: "A picture is worth a thousand words.", syllables: "A pic-ture is worth a thou-sand words.", translation: "一圖勝千言。"},
        {text: "Tongue twisters twist tongues terribly.", syllables: "Tongue twist-ers twist tongues ter-ri-bly.", translation: "繞口令讓舌頭打結得厲害。"},
        {text: "A watched pot never boils.", syllables: "A watched pot nev-er boils.", translation: "心急水不沸。"},
        {text: "Curiosity killed the cat.", syllables: "Cu-ri-o-si-ty killed the cat.", translation: "好奇心害死貓。"},
        {text: "Every dog has its day.", syllables: "Ev-e-ry dog has its day.", translation: "人人皆有得意日。"},
        {text: "Jack and Jill went up the hill to fetch a pail of water.", syllables: "Jack and Jill went up the hill to fetch a pail of wa-ter.", translation: "傑克和吉爾上山取水。"},
        {text: "If you can dream it, you can do it.", syllables: "If you can dream it, you can do it.", translation: "如果你能夢想它，你就能實現它。"},
        {text: "When in Rome, do as the Romans do.", syllables: "When in Rome, do as the Ro-mans do.", translation: "入鄉隨俗。"},
        {text: "The squeaky wheel gets the grease.", syllables: "The squea-ky wheel gets the grease.", translation: "吵鬧的輪子有油加。"},
        {text: "The pen is mightier than the sword.", syllables: "The pen is might-i-er than the sword.", translation: "筆比劍更強大。"},
        {text: "Beauty is in the eye of the beholder.", syllables: "Beau-ty is in the eye of the be-hold-er.", translation: "美是見仁見智的。"},
        {text: "It takes two to tango.", syllables: "It takes two to tan-go.", translation: "一個巴掌拍不響。"},
        {text: "Better safe than sorry.", syllables: "Bet-ter safe than sor-ry.", translation: "小心駛得萬年船。"},
        {text: "Out of sight, out of mind.", syllables: "Out of sight, out of mind.", translation: "眼不見為淨。"},
        {text: "You reap what you sow.", syllables: "You reap what you sow.", translation: "種瓜得瓜，種豆得豆。"},
        {text: "Don't put all your eggs in one basket.", syllables: "Don't put all your eggs in one bas-ket.", translation: "不要把所有雞蛋放在一個籃子裡。"},
        {text: "A rolling stone gathers no moss.", syllables: "A roll-ing stone gath-ers no moss.", translation: "滾石不生苔。"},
        {text: "Two wrongs don't make a right.", syllables: "Two wrongs don't make a right.", translation: "以惡報惡不能成為正義。"},
        {text: "Birds of a feather flock together.", syllables: "Birds of a feath-er flock to-geth-er.", translation: "物以類聚，人以群分。"},
        {text: "Practice makes perfect.", syllables: "Prac-tice makes per-fect.", translation: "熟能生巧。"},
        {text: "Slow and steady wins the race.", syllables: "Slow and stead-y wins the race.", translation: "穩紮穩打贏得比賽。"},
        {text: "Actions speak louder than words.", syllables: "Ac-tions speak loud-er than words.", translation: "行動勝於言語。"}
]
]
    ]
};
